config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/show'

  resources :projects

  resource :dashboard do
    member do
      get 'show'
    end
  end

  root 'dashboard#show'

end

app/models/project.rb
class Project < ActiveRecord::Base

 MUTANT_DIR = 'mutant'
 MUTANT_REPORT = 'mutant_report.html'
 RESULTS_NOT_READY_TEMPLATE = 'results_not_ready.html'

# validates :repository, presence:true
  validates :repository,
    format: { with: /git@github.com:.*.git/, message: 'Repository must be given in the git@github... format'}

  def name
    repository.match(/\/(.*).git/)[1]
  end

  def result
    if last_result
      "#{last_result}%"
    else
      'Never run'
    end
  end

  def last_commit
    (commit || 'not yet run')[0..10]
  end

  def public_results_file
    if File.exists?(results_file)
      make_results_public
      File.join(public_dir, mutant_report).sub(/.*\/public\//, '')
    else
      RESULTS_NOT_READY_TEMPLATE
    end
  end

  def project_dir
    File.join(Biohazard.mutant_directory, name)
  end

  def results_dir
    File.join(project_dir, MUTANT_DIR)
  end

  def results_file
    File.join(project_dir, mutant_report)
  end

  def mutant_report
    File.join(MUTANT_DIR, MUTANT_REPORT)
  end

  private

  def make_results_public
    unless Dir.exists?(public_dir)
      Dir.mkdir(public_dir)
    end
    FileUtils.cp_r(results_dir, public_dir)
  end

  def public_dir
    "#{Rails.root}/public/#{name}"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @projects = Project.all
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.all
  end

  # GET /projects/1
  def show
    if File.exists?(@project.results_file)
      @project.make_results_public

      render text: File.open(@project.results_file)
    else
      render text: 'Mutant has not yet been run on this project. Wait some minutes'
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def project_params
      params.require(:project).permit(:repository, :last_run, :last_result, :branch, :command)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper

  #A color acording to the achieved percentage
  def rgb_values(percentage)
    percentage = 0 if percentage.nil?
    # 255 is a strongly unpleasant color in most browsers
    g=(225*percentage)/100
    r=(225*(100-percentage))/100;
    b=0
    "rgb(#{r}, #{g}, #{b})"
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/dashboard/show.html.erb
<h1 class='page-header'>
	Results
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary pull-right' %>
</h1>

<div class='row'>
	<% @projects.each do |project| %>
	  <a href='<%=project.public_results_file%>' >
		<div class='dash-unit' style="background-color: <%= rgb_values(project.last_result)%>">
			<h1><%= project.name.capitalize %></h1>
			<h2><%= project.result %></h2>
			<div class='branch'><%= project.branch %></div>
			<div class='commit'><%= project.last_commit %></div>
			<div class='date'><%= project.last_run%></div>
		</div>
	  </a>

	<% end %>

	<div class='dash-unit'>
		<div class='date'>2013/02/21 10:20:21</div>
		<h1>Project name</h1>
		<h2>Percentage</h2>
	</div>

	<div class='dash-unit'>
		<h1>Project name</h1>
		<h2>Percentage</h2>
	</div>
</div>

<div class='row'>
	<div class='dash-unit'>
		even more
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Infestation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class='container'>
  <%= yield %>
</div>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :repository, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :repository, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :branch, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :branch, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :command, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :command, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                projects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:repository) %></th>
      <th><%= model_class.human_attribute_name(:last_run) %></th>
      <th><%= model_class.human_attribute_name(:last_result) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.id, project_path(project) %></td>
        <td><%= project.repository %></td>
        <td><%= project.last_run %></td>
        <td><%= project.last_result %></td>
        <td><%=l project.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_project_path(project), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      project_path(project),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_project_path,
            :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:repository) %>:</strong></dt>
  <dd><%= @project.repository %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_run) %>:</strong></dt>
  <dd><%= @project.last_run %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_result) %>:</strong></dt>
  <dd><%= @project.last_result %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              projects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_project_path(@project), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              project_path(@project),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>